import { MigrationInterface, QueryRunner } from "typeorm";

export class Sh1744544599803 implements MigrationInterface {
    name = 'Sh1744544599803'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "permissions" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "first_name" character varying, "last_name" character varying, "phone" character varying, "email" character varying NOT NULL, "password" character varying, "status" character varying NOT NULL DEFAULT 'active', "profileUrl" character varying, "isAdmin" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roleId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_8515e60a2cc41584fa4784f52ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."loan_verifications_status_enum" AS ENUM('Approved', 'Rejected')`);
        await queryRunner.query(`CREATE TABLE "loan_verifications" ("id" SERIAL NOT NULL, "notes" character varying, "status" "public"."loan_verifications_status_enum" NOT NULL DEFAULT 'Approved', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "loanId" integer, "memberId" integer, "groupMemberId" integer, CONSTRAINT "PK_83e764f295baca7cbf77e2fefad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."fines_reason_enum" AS ENUM('Late Contribution', 'Absenteeism', 'Loan Default', 'Other')`);
        await queryRunner.query(`CREATE TABLE "fines" ("id" SERIAL NOT NULL, "reason" "public"."fines_reason_enum" NOT NULL DEFAULT 'Other', "amount" integer NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "memberId" integer, "groupMemberId" integer, "groupId" integer, "contributionId" integer, "branchId" integer, "createdById" integer, "loanId" integer, CONSTRAINT "PK_b706344bc8943ab7a88ed5d312e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expense_categories" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426" UNIQUE ("name"), CONSTRAINT "PK_d0ef31e189d9523461215b62775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" SERIAL NOT NULL, "amount" integer NOT NULL, "name" character varying NOT NULL, "attachment" json, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "groupId" integer, "seasonId" integer, "createdById" integer, "branchId" integer, "expenseCategoryId" integer, "paymentMethodId" integer, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "accountNumber" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a793d7354d7c3aaf76347ee5a66" UNIQUE ("name"), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loan_payments" ("id" SERIAL NOT NULL, "date" date NOT NULL, "amount" numeric(15,2) NOT NULL, "referenceNumber" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "loanId" integer, "paymentMethodId" integer, "receivedById" integer, "groupId" integer, "seasonId" integer, CONSTRAINT "PK_db75e38243b5f2cb9e728da4d0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."loans_loantype_enum" AS ENUM('Emergency', 'Business', 'Education', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."loans_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."loans_paymentfrequency_enum" AS ENUM('Monthly', 'Weekly', 'Daily')`);
        await queryRunner.query(`CREATE TABLE "loans" ("id" SERIAL NOT NULL, "loanType" "public"."loans_loantype_enum" NOT NULL DEFAULT 'Other', "status" "public"."loans_status_enum" NOT NULL DEFAULT 'pending', "amount" integer NOT NULL, "loanTerms" character varying, "interestRate" integer NOT NULL, "paymentFrequency" "public"."loans_paymentfrequency_enum" NOT NULL DEFAULT 'Monthly', "completedAt" TIMESTAMP, "attachments" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "groupMemberId" integer, "memberId" integer, "seasonId" integer, "createdById" integer, "groupId" integer, "branchId" integer, CONSTRAINT "PK_5c6942c1e13e4de135c5203ee61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."seasons_status_enum" AS ENUM('active', 'completed')`);
        await queryRunner.query(`CREATE TABLE "seasons" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "start" date NOT NULL, "end" date NOT NULL, "status" "public"."seasons_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb8ed53b5fe109dcd4a4449ec9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contributions_contributiontype_enum" AS ENUM('solidarity', 'saving')`);
        await queryRunner.query(`CREATE TABLE "contributions" ("id" SERIAL NOT NULL, "depositAmount" integer NOT NULL, "contributionType" "public"."contributions_contributiontype_enum" NOT NULL DEFAULT 'saving', "currentSavingAmount" integer NOT NULL, "currentSolidalityAmount" integer NOT NULL, "beforeSavingAmount" integer NOT NULL, "beforeSolidalityAmount" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "memberId" integer, "groupMemberId" integer, "seasonId" integer, "groupId" integer, "paymentMethodId" integer, "branchId" integer, "receivedById" integer, CONSTRAINT "PK_ca2b4f39eb9e32a61278c711f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" SERIAL NOT NULL, "loanEligibility" boolean NOT NULL DEFAULT false, "numberOfShares" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "memberId" integer, "groupId" integer, "branchId" integer, CONSTRAINT "PK_86446139b2c96bfd0f3b8638852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."members_gender_enum" AS ENUM('Male', 'Female', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."members_marriagestatus_enum" AS ENUM('Single', 'Married', 'Divorced', 'Widowed')`);
        await queryRunner.query(`CREATE TABLE "members" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "fullNames" character varying NOT NULL, "gender" "public"."members_gender_enum" NOT NULL DEFAULT 'Other', "phone" character varying, "marriageStatus" "public"."members_marriagestatus_enum" NOT NULL DEFAULT 'Single', "idNumber" character varying NOT NULL, "country" character varying, "currentAddress" character varying, "joinedAt" date NOT NULL, "sourceOfIncome" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "branchId" integer, CONSTRAINT "UQ_0425019e5785b5e58dcfade4d92" UNIQUE ("idNumber"), CONSTRAINT "PK_28b53062261b996d9c99fa12404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "address" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "usersId" integer, CONSTRAINT "UQ_8387ed27b3d4ca53ec3fc7b029c" UNIQUE ("name"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."groups_meetingfrequency_enum" AS ENUM('Weekly', 'Bi-weekly', 'Monthly', 'Quarterly')`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "meetingFrequency" "public"."groups_meetingfrequency_enum" NOT NULL DEFAULT 'Monthly', "location" character varying, "pricePerShare" integer NOT NULL, "minShares" integer NOT NULL, "maxShares" integer NOT NULL, "solidarityAmount" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "presidentId" integer, "accountantId" integer, "secretaryId" integer, "branchId" integer, CONSTRAINT "UQ_664ea405ae2a10c264d582ee563" UNIQUE ("name"), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" SERIAL NOT NULL, "date" date NOT NULL, "attendances" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "groupId" integer, CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_8e913e288156c133999341156ad" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset" ADD CONSTRAINT "FK_05baebe80e9f8fab8207eda250c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" ADD CONSTRAINT "FK_7c7e5fe85b8b72c76e43aac7a0a" FOREIGN KEY ("loanId") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" ADD CONSTRAINT "FK_0bf7ec6cb583c4c5bb41f810f6e" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" ADD CONSTRAINT "FK_b59d5ef4c8519ae24ae5630d223" FOREIGN KEY ("groupMemberId") REFERENCES "group_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_1ffdae89c0efa12cc7056688ea4" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_00713edad908250a41cac26fa43" FOREIGN KEY ("groupMemberId") REFERENCES "group_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_e7b864fd4b599cd69c4336d741d" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_72a9a507009efd1d123b050f4c0" FOREIGN KEY ("contributionId") REFERENCES "contributions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_e9f7a7bfc5bb2714000628e2155" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_0bad14f05d1eba9b644a68c2f85" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fines" ADD CONSTRAINT "FK_361265ed80a33c93c0665b300b1" FOREIGN KEY ("loanId") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_c4601c36c8b1326e9427e1aca3b" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_11ab31f33be3616e924638fd073" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_4f3e45915b1db0536a90400b419" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_eed45f691864a80afbd9e2178ce" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_73f9d7b09a88a44d3d0f639b187" FOREIGN KEY ("expenseCategoryId") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_3258675805604ac8b86cfe5e556" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_c0268488cc84d23c1e5c6c1910d" FOREIGN KEY ("loanId") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_b08f045698687ebbe8cb8faabc0" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_a8291a1d4243c367e45071a6cd4" FOREIGN KEY ("receivedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_7e5519981e50912e34f1099d60f" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_f2153d39fe2b0b051d5578eb292" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_bab42b3dd99044859299bbb7ede" FOREIGN KEY ("groupMemberId") REFERENCES "group_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_95f07ed85a66f8cca696347f529" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_8d6ff7ef7950ee953908e80b146" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_52c527ba1e68e448057ea05ea18" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_81a38fb3d337b7989dbe3646de5" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_814fcd9d451f71c0fcd128981d8" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_d100de32b0aedd205c9d7a9c34c" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_231f802b640563c741512e242af" FOREIGN KEY ("groupMemberId") REFERENCES "group_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_f2c254d069a02001fba759eeb74" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_00dcd076e527ab82419e2382ca5" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_2e3d03ba19bd4daffb9f14a2834" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_2da671d7341819baff302961621" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_0473c5881d1291fed6572aa2cf9" FOREIGN KEY ("receivedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_198a0576d65b3e038bca49ac474" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_ea782afb09083036fc57d2c0dc8" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_f496c330bf399940f4dce994d47" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_ad73c99f92f5cefe28c7ee11137" FOREIGN KEY ("usersId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_86e7c75bc0f689d9d73fad1fd04" FOREIGN KEY ("presidentId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_a00fbf08ebb5554e3fec26e3a5c" FOREIGN KEY ("accountantId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_ff224acc1e3007172ccd96500cb" FOREIGN KEY ("secretaryId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_3d802bbcffd407a85b6e5a60759" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_960f6ee431b5d708e91021fc23e" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_960f6ee431b5d708e91021fc23e"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_3d802bbcffd407a85b6e5a60759"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_ff224acc1e3007172ccd96500cb"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_a00fbf08ebb5554e3fec26e3a5c"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_86e7c75bc0f689d9d73fad1fd04"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_ad73c99f92f5cefe28c7ee11137"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_f496c330bf399940f4dce994d47"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_ea782afb09083036fc57d2c0dc8"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_198a0576d65b3e038bca49ac474"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_0473c5881d1291fed6572aa2cf9"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_2da671d7341819baff302961621"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_2e3d03ba19bd4daffb9f14a2834"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_00dcd076e527ab82419e2382ca5"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_f2c254d069a02001fba759eeb74"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_231f802b640563c741512e242af"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_d100de32b0aedd205c9d7a9c34c"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_814fcd9d451f71c0fcd128981d8"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_81a38fb3d337b7989dbe3646de5"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_52c527ba1e68e448057ea05ea18"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_8d6ff7ef7950ee953908e80b146"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_95f07ed85a66f8cca696347f529"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_bab42b3dd99044859299bbb7ede"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_f2153d39fe2b0b051d5578eb292"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_7e5519981e50912e34f1099d60f"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_a8291a1d4243c367e45071a6cd4"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_b08f045698687ebbe8cb8faabc0"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_c0268488cc84d23c1e5c6c1910d"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_3258675805604ac8b86cfe5e556"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_73f9d7b09a88a44d3d0f639b187"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_eed45f691864a80afbd9e2178ce"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_4f3e45915b1db0536a90400b419"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_11ab31f33be3616e924638fd073"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_c4601c36c8b1326e9427e1aca3b"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_361265ed80a33c93c0665b300b1"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_0bad14f05d1eba9b644a68c2f85"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_e9f7a7bfc5bb2714000628e2155"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_72a9a507009efd1d123b050f4c0"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_e7b864fd4b599cd69c4336d741d"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_00713edad908250a41cac26fa43"`);
        await queryRunner.query(`ALTER TABLE "fines" DROP CONSTRAINT "FK_1ffdae89c0efa12cc7056688ea4"`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" DROP CONSTRAINT "FK_b59d5ef4c8519ae24ae5630d223"`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" DROP CONSTRAINT "FK_0bf7ec6cb583c4c5bb41f810f6e"`);
        await queryRunner.query(`ALTER TABLE "loan_verifications" DROP CONSTRAINT "FK_7c7e5fe85b8b72c76e43aac7a0a"`);
        await queryRunner.query(`ALTER TABLE "password_reset" DROP CONSTRAINT "FK_05baebe80e9f8fab8207eda250c"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_8e913e288156c133999341156ad"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TYPE "public"."groups_meetingfrequency_enum"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP TYPE "public"."members_marriagestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."members_gender_enum"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP TABLE "contributions"`);
        await queryRunner.query(`DROP TYPE "public"."contributions_contributiontype_enum"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP TYPE "public"."seasons_status_enum"`);
        await queryRunner.query(`DROP TABLE "loans"`);
        await queryRunner.query(`DROP TYPE "public"."loans_paymentfrequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loans_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loans_loantype_enum"`);
        await queryRunner.query(`DROP TABLE "loan_payments"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TABLE "expense_categories"`);
        await queryRunner.query(`DROP TABLE "fines"`);
        await queryRunner.query(`DROP TYPE "public"."fines_reason_enum"`);
        await queryRunner.query(`DROP TABLE "loan_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."loan_verifications_status_enum"`);
        await queryRunner.query(`DROP TABLE "password_reset"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
    }

}
